#85 Add filter by region, district, locality.
Entea/covid-supply-info pull request #99
Opened 2020-03-29 23:42 UTC by Isabek

2020-03-29 23:48 UTC, Isabek commented on frontend/components/layout/Header.jsx
> +    onRegionChange(region) {
Говнокод. Как надо делать @elzaresen @Diyahon ?

2020-03-29 23:48 UTC, Isabek commented on frontend/pages/index.js
> +    componentDidMount() {
Говнокод. Как надо делать @elzaresen @Diyahon ? Надо прикрутить Redux.

2020-03-29 23:52 UTC, BupycHuk commented on frontend/reducers/hospitalsReducer.js
Вот это точно не пример хорошего форматирования

2020-03-29 23:52 UTC, BupycHuk commented on frontend/styles/_main.scss
> +  max-width: 220px;
Это почему?

2020-03-29 23:56 UTC, Isabek commented on frontend/components/layout/Header.jsx
> +            );
@BupycHuk тут не очень хорошо получилось )

2020-03-29 23:56 UTC, Isabek commented on frontend/pages/index.js
> +    componentDidMount() {
@BupycHuk тут не получилось исрользовать fetchHospitalsAction. Что за объект не понял. Выглядит как promise, но когда вызываешь then посылает ...

2020-03-29 23:56 UTC, Isabek commented on frontend/reducers/hospitalsReducer.js
> +	import * as Actions from '../actions/hospitals'
```suggestion
import * as Actions from '../actions/hospitals'
```

2020-03-29 23:56 UTC, Isabek commented on frontend/styles/_main.scss
> +  max-width: 220px;
http://joxi.net/a2X53bPIDJppMA

2020-03-29 23:59 UTC, BupycHuk commented on frontend/styles/_main.scss
> +  max-width: 220px;
Я понимаю где, но в чем была проблема?

2020-03-30 00:01 UTC, BupycHuk commented on frontend/components/layout/Header.jsx
> +            );
А нельзя просто {regionValue: region, districtValue: null, localityValur: null}?

2020-03-30 00:10 UTC, Isabek commented on frontend/styles/_main.scss
> +  max-width: 220px;
Названия областей длинные, оказывается.

2020-03-30 08:41 UTC, elzaresen requested changes

2020-03-30 08:41 UTC, elzaresen commented on frontend/pages/index.js
> +// const mapStateToProps = (state) => {
Раскоментить нужно, это подрубается redux

2020-03-30 08:41 UTC, elzaresen commented on frontend/pages/index.js
> +        axios
Можно здесь использовать экшн, в экшн добавить доп параметры

2020-03-30 08:41 UTC, elzaresen commented on frontend/components/main/index.js
> +
Добавить state

2020-03-30 08:41 UTC, elzaresen commented on frontend/components/main/index.js
> +    componentDidMount() {
В принципе правильно но лучше
`
 this.setState({
     hospitals: []
 })
`

2020-03-30 08:41 UTC, elzaresen commented on frontend/reducers/districtsReducer.js
> +				count: action.data.length,
action.data это то что возвращает с API, results = action.data.results

2020-03-30 16:50 UTC, merged